language: python
python:
    - "3.5"
    - "3.6"
install:
 - pip install nose
 - pip install coveralls
 - pip install coverage
script:
 - nosetests
 - coverage run -m nose
after_success:
 - coveralls
